import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const ppMori = localFont({
  src: [
    {
      path: "../public/fonts/PPMori-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/PPMori-ExtralightItalic.woff2",
      weight: "200",
      style: "italic",
    },
    {
      path: "../public/fonts/PPMori-Semibold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../public/fonts/PPMori-Black.woff2",
      weight: "900",
      style: "normal",
    },
    {
      path: "../public/fonts/PPMori-BlackItalic.woff2",
      weight: "900",
      style: "italic",
    },
  ],
  variable: "--font-ppmori",
});

export const metadata: Metadata = {
  title: "UNMARKED—LABEL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${ppMori.variable} antialiased`}>
        <div className="fixed top-6 left-6 z-[60] flex items-center gap-2 font-sans text-sm pointer-events-none mix-blend-difference text-white">
          <span className="uppercase">A LIVING PROJECT</span>
          <span className="text-white/50">V.01</span>
        </div>
        {children}
      </body>
    </html>
  );
}
